/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nodes
         * @description List nodes with optional filtering, search, and pagination.
         */
        get: operations["list_nodes_api_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Filters
         * @description 返回可用的协议和地区列表（带计数），给前端筛选下拉用。
         */
        get: operations["get_node_filters_api_nodes_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node
         * @description Get a single node with full details.
         */
        get: operations["get_node_api_nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node History
         * @description Get verification history for a node.
         */
        get: operations["get_node_history_api_nodes__node_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Global aggregate statistics.
         */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/protocols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Protocol Stats
         * @description Node counts grouped by protocol.
         */
        get: operations["get_protocol_stats_api_stats_protocols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Stats
         * @description Node counts and average latency grouped by region.
         */
        get: operations["get_region_stats_api_stats_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description List all configured data sources with their runtime status.
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/clash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscription Clash
         * @description Generate a Clash YAML subscription.
         */
        get: operations["subscription_clash_api_subscriptions_clash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/v2ray": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscription V2Ray
         * @description Generate a Base64-encoded V2Ray subscription.
         */
        get: operations["subscription_v2ray_api_subscriptions_v2ray_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/plain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscription Plain
         * @description Generate a plain HTTP/SOCKS proxy list (proxies.txt equivalent).
         */
        get: operations["subscription_plain_api_subscriptions_plain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Service health check.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Refresh
         * @description Manually trigger a full pipeline run (requires admin API key).
         */
        post: operations["trigger_refresh_api_admin_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description Poll the status of a pipeline task.
         */
        get: operations["get_task_status_api_admin_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Node
         * @description 软删一个节点，标记 is_deleted 不真删。
         */
        delete: operations["delete_node_api_admin_nodes__node_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Source
         * @description 新建一个数据源。
         */
        post: operations["create_source_api_admin_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description 硬删一个数据源。
         */
        delete: operations["delete_source_api_admin_sources__source_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Source
         * @description 改数据源，只动 body 里非 None 的字段。
         */
        patch: operations["update_source_api_admin_sources__source_id__patch"];
        trace?: never;
    };
    "/api/admin/sources/{source_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source Logs
         * @description 某个数据源最近的抓取日志，按时间倒序。
         */
        get: operations["get_source_logs_api_admin_sources__source_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics
         * @description 给后台用的聚合指标：节点统计 + 数据源统计 + 最近一次流水线状态。
         */
        get: operations["get_metrics_api_admin_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/metrics/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics Trend
         * @description 最近 7 天每天的检查数和存活数，给仪表盘趋势图用。
         */
        get: operations["get_metrics_trend_api_admin_metrics_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FilterOption */
        FilterOption: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** FiltersResponse */
        FiltersResponse: {
            /** Protocols */
            protocols: components["schemas"]["FilterOption"][];
            /** Regions */
            regions: components["schemas"]["FilterOption"][];
        };
        /** GlobalStats */
        GlobalStats: {
            /** Total Nodes */
            total_nodes: number;
            /** Alive Nodes */
            alive_nodes: number;
            /** Dead Nodes */
            dead_nodes: number;
            /** Survival Rate */
            survival_rate: number;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** Total Sources */
            total_sources: number;
            /** Enabled Sources */
            enabled_sources: number;
            /** Last Updated */
            last_updated: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Total Nodes */
            total_nodes: number;
            /** Alive Nodes */
            alive_nodes: number;
            /** Last Updated */
            last_updated: string | null;
        };
        /** MetricsLastPipeline */
        MetricsLastPipeline: {
            /** Status */
            status: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Alive Nodes */
            alive_nodes?: number | null;
        };
        /** MetricsNodes */
        MetricsNodes: {
            /** Total */
            total: number;
            /** Alive */
            alive: number;
            /** By Protocol */
            by_protocol: {
                [key: string]: number;
            };
            /** By Region Top5 */
            by_region_top5: components["schemas"]["RegionCount"][];
        };
        /** MetricsResponse */
        MetricsResponse: {
            nodes: components["schemas"]["MetricsNodes"];
            sources: components["schemas"]["MetricsSources"];
            last_pipeline?: components["schemas"]["MetricsLastPipeline"] | null;
        };
        /** MetricsSources */
        MetricsSources: {
            /** Total */
            total: number;
            /** Enabled */
            enabled: number;
        };
        /** NodeDetail */
        NodeDetail: {
            /** Id */
            id: number;
            /** Protocol */
            protocol: string;
            /** Server */
            server: string;
            /** Port */
            port: number;
            /** Network */
            network: string;
            /** Tls */
            tls: boolean;
            /** Remark */
            remark: string;
            /** Region */
            region: string;
            /** Source Name */
            source_name: string;
            /** Is Alive */
            is_alive: boolean;
            /** Last Latency Ms */
            last_latency_ms: number | null;
            /** Last Checked At */
            last_checked_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Raw Link */
            raw_link: string;
            /** Auth Secret */
            auth_secret: string;
            /** Transport Config */
            transport_config: string;
            /** Fail Reason */
            fail_reason: string | null;
        };
        /** NodeOut */
        NodeOut: {
            /** Id */
            id: number;
            /** Protocol */
            protocol: string;
            /** Server */
            server: string;
            /** Port */
            port: number;
            /** Network */
            network: string;
            /** Tls */
            tls: boolean;
            /** Remark */
            remark: string;
            /** Region */
            region: string;
            /** Source Name */
            source_name: string;
            /** Is Alive */
            is_alive: boolean;
            /** Last Latency Ms */
            last_latency_ms: number | null;
            /** Last Checked At */
            last_checked_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PaginatedResponse[NodeOut] */
        PaginatedResponse_NodeOut_: {
            /** Items */
            items: components["schemas"]["NodeOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ProtocolStat */
        ProtocolStat: {
            /** Protocol */
            protocol: string;
            /** Total */
            total: number;
            /** Alive */
            alive: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /**
             * Verify
             * @default true
             */
            verify: boolean;
        };
        /** RegionCount */
        RegionCount: {
            /** Region */
            region: string;
            /** Count */
            count: number;
        };
        /** RegionStat */
        RegionStat: {
            /** Region */
            region: string;
            /** Total */
            total: number;
            /** Alive */
            alive: number;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
        };
        /** SourceCreateRequest */
        SourceCreateRequest: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Category
             * @default free_node_sources
             */
            category: string;
            /**
             * Source Type
             * @default node
             */
            source_type: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Decode Base64
             * @default false
             */
            decode_base64: boolean;
            /**
             * Proxy Scheme
             * @default http
             */
            proxy_scheme: string;
        };
        /** SourceFetchLogOut */
        SourceFetchLogOut: {
            /** Id */
            id: number;
            /** Source Id */
            source_id: number | null;
            /** Status */
            status: string | null;
            /** New Count */
            new_count: number;
            /** Error */
            error: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Category */
            category: string;
            /** Source Type */
            source_type: string;
            /** Enabled */
            enabled: boolean;
            /** Decode Base64 */
            decode_base64: boolean;
            /** Proxy Scheme */
            proxy_scheme: string;
            /** Update Interval */
            update_interval: string | null;
            /** Protocols */
            protocols: string[];
            /** Last Fetch At */
            last_fetch_at: string | null;
            /** Last Fetch Status */
            last_fetch_status: string | null;
            /** Last Nodes Added */
            last_nodes_added: number;
            /** Last Error */
            last_error: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SourceUpdateRequest */
        SourceUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Url */
            url?: string | null;
            /** Category */
            category?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Decode Base64 */
            decode_base64?: boolean | null;
            /** Proxy Scheme */
            proxy_scheme?: string | null;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Date */
            date: string;
            /** Checked */
            checked: number;
            /** Alive */
            alive: number;
        };
        /** TrendResponse */
        TrendResponse: {
            /** Days */
            days: components["schemas"]["TrendPoint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_nodes_api_nodes_get: {
        parameters: {
            query?: {
                /** @description Filter by protocol (vmess/vless/ss/trojan) */
                protocol?: string | null;
                /** @description Filter by region */
                region?: string | null;
                /** @description Filter by liveness */
                alive?: boolean | null;
                /** @description Max latency in ms */
                max_latency?: number | null;
                /** @description Search remark/region */
                q?: string | null;
                limit?: number;
                offset?: number;
                /** @description Sort: updated|latency|newest */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_NodeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_filters_api_nodes_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    get_node_api_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_history_api_nodes__node_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStats"];
                };
            };
        };
    };
    get_protocol_stats_api_stats_protocols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolStat"][];
                };
            };
        };
    };
    get_region_stats_api_stats_regions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionStat"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: {
                /** @description Filter by enabled status */
                enabled?: boolean | null;
                /** @description Filter by category (nodes/proxies) */
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscription_clash_api_subscriptions_clash_get: {
        parameters: {
            query?: {
                protocol?: string | null;
                region?: string | null;
                alive?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscription_v2ray_api_subscriptions_v2ray_get: {
        parameters: {
            query?: {
                protocol?: string | null;
                region?: string | null;
                alive?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscription_plain_api_subscriptions_plain_get: {
        parameters: {
            query?: {
                alive?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    trigger_refresh_api_admin_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_admin_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_api_admin_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_api_admin_sources_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_admin_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_admin_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_logs_api_admin_sources__source_id__logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFetchLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_admin_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_trend_api_admin_metrics_trend_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
