export interface Platform {
  name: string; // 仓库名
  owner: string; // 仓库 owner
  url: string; // GitHub 链接
  description: string; // 中文简介（1-2句话）
  protocols: string[]; // 支持的协议
  updateFrequency: string; // 更新频率
  stars: string; // 星标级别（如 "10k+", "5k+", "1k+"）
  format: string[]; // 输出格式（如 ["Clash", "V2Ray", "Base64"]）
  featured: boolean; // 是否推荐
  difficulty: "beginner" | "intermediate" | "advanced"; // 使用难度
  recommendedFor: string[]; // 推荐场景 / 适用人群
  compatibility: number; // 兼容性评分（0-100）
}

export const platforms: Platform[] = [
  {
    name: "V2ray-Configs",
    owner: "barry-far",
    url: "https://github.com/barry-far/V2ray-Configs",
    description:
      "聚合多个公开订阅源的 V2Ray 配置，每日自动合并去重并输出 Base64 与分段格式，覆盖面广且更新稳定。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "10k+",
    format: ["V2Ray", "Base64"],
    featured: true,
    difficulty: "beginner",
    recommendedFor: ["v2rayN用户", "v2rayNG用户", "每日更新", "新手入门"],
    compatibility: 95,
  },
  {
    name: "free",
    owner: "freefq",
    url: "https://github.com/freefq/free",
    description:
      "老牌免费节点聚合仓库，长期维护，提供 V2Ray 与 Clash 订阅，节点来源透明、更新勤勉。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "10k+",
    format: ["V2Ray", "Clash", "Base64"],
    featured: true,
    difficulty: "beginner",
    recommendedFor: ["Clash用户", "v2rayN用户", "每日更新", "稳定老牌"],
    compatibility: 96,
  },
  {
    name: "V2rayAggregator",
    owner: "mahdibland",
    url: "https://github.com/mahdibland/V2rayAggregator",
    description:
      "强大的 V2Ray 订阅聚合器，内置订阅抓取、去重、连通性检测与 Clash/V2Ray/Sing-box 多格式输出。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "5k+",
    format: ["Clash", "V2Ray", "Base64", "Sing-box"],
    featured: true,
    difficulty: "intermediate",
    recommendedFor: ["进阶用户", "多格式", "Sing-box", "自动检测"],
    compatibility: 90,
  },
  {
    name: "v2rayfree",
    owner: "aiboboxx",
    url: "https://github.com/aiboboxx/v2rayfree",
    description:
      "提供 V2Ray 与 Clash 免费节点订阅，更新频率高，附带节点测速与可用性筛选。",
    protocols: ["VLESS", "VMess", "Trojan"],
    updateFrequency: "每日",
    stars: "5k+",
    format: ["V2Ray", "Clash", "Base64"],
    featured: true,
    difficulty: "beginner",
    recommendedFor: ["v2rayN用户", "Clash用户", "测速筛选", "每日更新"],
    compatibility: 93,
  },
  {
    name: "Free-servers",
    owner: "Pawdroid",
    url: "https://github.com/Pawdroid/Free-servers",
    description:
      "免费服务器与代理节点聚合项目，输出 V2Ray 与 Clash 订阅，适合快速试用与学习研究。",
    protocols: ["VLESS", "VMess", "SS"],
    updateFrequency: "每日",
    stars: "5k+",
    format: ["V2Ray", "Clash", "Base64"],
    featured: true,
    difficulty: "beginner",
    recommendedFor: ["新手入门", "快速试用", "Clash用户", "v2rayN用户"],
    compatibility: 91,
  },
  {
    name: "treble",
    owner: "mfbpn",
    url: "https://github.com/mfbpn/treble",
    description:
      "基于 Clash Meta 内核的免费节点聚合，每日自动抓取并生成 Clash 订阅，附带筛选规则。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "5k+",
    format: ["Clash"],
    featured: true,
    difficulty: "intermediate",
    recommendedFor: ["Clash Meta用户", "规则筛选", "每日更新"],
    compatibility: 88,
  },
  {
    name: "NoMoreWalls",
    owner: "peasoft",
    url: "https://github.com/peasoft/NoMoreWalls",
    description:
      "无墙节点订阅仓库，每日合并多个公开来源并输出 Clash 与 V2Ray 格式，附带使用文档。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "5k+",
    format: ["Clash", "V2Ray", "Base64"],
    featured: true,
    difficulty: "beginner",
    recommendedFor: ["新手入门", "多协议", "每日更新", "附带文档"],
    compatibility: 92,
  },
  {
    name: "clash-freenode",
    owner: "openrunner",
    url: "https://github.com/openrunner/clash-freenode",
    description:
      "面向 Clash 用户的免费节点订阅，每日更新并附带规则集，开箱即用。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["Clash"],
    featured: false,
    difficulty: "beginner",
    recommendedFor: ["Clash用户", "开箱即用", "每日更新"],
    compatibility: 87,
  },
  {
    name: "v2ray",
    owner: "clowndoy",
    url: "https://github.com/clowndoy/v2ray",
    description:
      "V2Ray 免费节点聚合仓库，定期更新并提供 Base64 订阅链接，适合 v2rayN/v2rayNG 用户。",
    protocols: ["VLESS", "VMess", "Trojan"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["V2Ray", "Base64"],
    featured: false,
    difficulty: "beginner",
    recommendedFor: ["v2rayN用户", "v2rayNG用户", "Base64订阅"],
    compatibility: 86,
  },
  {
    name: "v2ray",
    owner: "V2rayCollector",
    url: "https://github.com/V2rayCollector/v2ray",
    description:
      "从多个公开渠道采集 V2Ray 节点并自动去重，输出标准订阅格式，更新勤勉。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["V2Ray", "Base64"],
    featured: false,
    difficulty: "beginner",
    recommendedFor: ["v2rayN用户", "自动去重", "每日更新"],
    compatibility: 85,
  },
  {
    name: "v2ray-configs",
    owner: "Epodonios",
    url: "https://github.com/Epodonios/v2ray-configs",
    description:
      "聚合 V2Ray 配置文件，每日合并公开订阅源并输出多格式订阅，附带使用说明。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["V2Ray", "Clash", "Base64"],
    featured: false,
    difficulty: "beginner",
    recommendedFor: ["新手入门", "多格式", "每日更新"],
    compatibility: 88,
  },
  {
    name: "telegram-configs-collector",
    owner: "soroushmirzaei",
    url: "https://github.com/soroushmirzaei/telegram-configs-collector",
    description:
      "自动采集 Telegram 频道中分享的代理配置，按协议分类输出，覆盖 VLESS/VMess/Trojan/SS。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["V2Ray", "Clash", "Base64", "Sing-box"],
    featured: false,
    difficulty: "intermediate",
    recommendedFor: ["进阶用户", "Telegram源", "多格式", "Sing-box"],
    compatibility: 84,
  },
  {
    name: "TelegramV2rayCollector",
    owner: "yebekhe",
    url: "https://github.com/yebekhe/TelegramV2rayCollector",
    description:
      "基于 Telegram 频道的 V2Ray 配置采集器，支持多协议并输出 Clash/V2Ray/Sing-box 订阅。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每小时",
    stars: "1k+",
    format: ["V2Ray", "Clash", "Base64", "Sing-box"],
    featured: false,
    difficulty: "intermediate",
    recommendedFor: ["高频更新", "Telegram源", "Sing-box", "进阶用户"],
    compatibility: 83,
  },
  {
    name: "v2ray",
    owner: "free18",
    url: "https://github.com/free18/v2ray",
    description:
      "免费 V2Ray 节点订阅仓库，定期更新并提供 Base64 链接，适合个人学习与测试。",
    protocols: ["VLESS", "VMess", "Trojan"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["V2Ray", "Base64"],
    featured: false,
    difficulty: "beginner",
    recommendedFor: ["个人学习", "测试", "v2rayN用户"],
    compatibility: 82,
  },
  {
    name: "PROXY-List",
    owner: "TheSpeedX",
    url: "https://github.com/TheSpeedX/PROXY-List",
    description:
      "高频更新的 HTTP/SOCKS4/SOCKS5 公开代理列表，提供 raw 文本与 JSON 格式，适合爬虫与命令行工具。",
    protocols: ["HTTP", "HTTPS", "SOCKS4", "SOCKS5"],
    updateFrequency: "每小时",
    stars: "10k+",
    format: ["HTTP代理", "Base64", "JSON"],
    featured: true,
    difficulty: "advanced",
    recommendedFor: ["爬虫", "命令行工具", "HTTP代理", "高频更新"],
    compatibility: 78,
  },
  {
    name: "free-proxy-list",
    owner: "proxifly",
    url: "https://github.com/proxifly/free-proxy-list",
    description:
      "免费代理列表仓库，提供 HTTP/SOCKS 代理并附带国家、延迟等元数据，支持多格式输出。",
    protocols: ["HTTP", "HTTPS", "SOCKS4", "SOCKS5"],
    updateFrequency: "每小时",
    stars: "1k+",
    format: ["HTTP代理", "JSON", "CSV", "TXT"],
    featured: false,
    difficulty: "advanced",
    recommendedFor: ["爬虫", "元数据筛选", "JSON/CSV"],
    compatibility: 75,
  },
  {
    name: "proxies",
    owner: "ErcinDedeoglu",
    url: "https://github.com/ErcinDedeoglu/proxies",
    description:
      "自动抓取并校验的公开代理列表，按协议与国家分类输出，更新频率高、质量较稳定。",
    protocols: ["HTTP", "HTTPS", "SOCKS4", "SOCKS5"],
    updateFrequency: "每小时",
    stars: "1k+",
    format: ["HTTP代理", "JSON", "TXT"],
    featured: false,
    difficulty: "advanced",
    recommendedFor: ["爬虫", "按国家分类", "HTTP代理"],
    compatibility: 76,
  },
  {
    name: "proxy-list",
    owner: "jetkai",
    url: "https://github.com/jetkai/proxy-list",
    description:
      "高频更新的代理列表聚合项目，自动校验可用性并按协议分类，附带在线 API 接口。",
    protocols: ["HTTP", "HTTPS", "SOCKS4", "SOCKS5"],
    updateFrequency: "每 5 分钟",
    stars: "1k+",
    format: ["HTTP代理", "JSON", "TXT"],
    featured: false,
    difficulty: "advanced",
    recommendedFor: ["爬虫", "API接口", "极高频更新"],
    compatibility: 74,
  },
  {
    name: "openproxylist",
    owner: "roosterkid",
    url: "https://github.com/roosterkid/openproxylist",
    description:
      "开源代理列表项目，自动抓取并校验 HTTP/SOCKS 代理，输出标准文本与 Base64 格式。",
    protocols: ["HTTP", "HTTPS", "SOCKS4", "SOCKS5"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["HTTP代理", "Base64", "TXT"],
    featured: false,
    difficulty: "advanced",
    recommendedFor: ["爬虫", "HTTP代理", "Base64"],
    compatibility: 73,
  },
  {
    name: "free-proxy-list",
    owner: "sanjusss",
    url: "https://github.com/sanjusss/free-proxy-list",
    description:
      "基于多源抓取与校验的免费代理列表，提供 HTTP/SOCKS 代理并按可用性排序。",
    protocols: ["HTTP", "HTTPS", "SOCKS4", "SOCKS5"],
    updateFrequency: "每小时",
    stars: "1k+",
    format: ["HTTP代理", "JSON", "TXT"],
    featured: false,
    difficulty: "advanced",
    recommendedFor: ["爬虫", "可用性排序", "JSON"],
    compatibility: 72,
  },
  {
    name: "telegram-proxy-collector",
    owner: "MoneroTalks",
    url: "https://github.com/MoneroTalks/telegram-proxy-collector",
    description:
      "采集 Telegram 频道分享的代理节点，覆盖 V2Ray 与 SOCKS 代理，按协议分类输出。",
    protocols: ["VLESS", "VMess", "Trojan", "SOCKS5"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["V2Ray", "Base64", "HTTP代理"],
    featured: false,
    difficulty: "intermediate",
    recommendedFor: ["Telegram源", "混合代理", "进阶用户"],
    compatibility: 80,
  },
  {
    name: "nodefree",
    owner: "NodefreeForMe",
    url: "https://github.com/NodefreeForMe/nodefree",
    description:
      "免费节点订阅仓库，每日更新并提供 Clash 与 V2Ray 格式，附带使用教程与客户端推荐。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["Clash", "V2Ray", "Base64"],
    featured: false,
    difficulty: "beginner",
    recommendedFor: ["新手入门", "附带教程", "Clash用户", "v2rayN用户"],
    compatibility: 89,
  },
  {
    name: "NodeV2ray",
    owner: "xrayfree",
    url: "https://github.com/xrayfree/NodeV2ray",
    description:
      "V2Ray/Xray 免费节点聚合仓库，定期更新并输出 Base64 订阅，适合 Xray 内核客户端。",
    protocols: ["VLESS", "VMess", "Trojan", "SS"],
    updateFrequency: "每日",
    stars: "1k+",
    format: ["V2Ray", "Base64"],
    featured: false,
    difficulty: "intermediate",
    recommendedFor: ["Xray内核", "v2rayN用户", "Base64订阅"],
    compatibility: 85,
  },
];
