# FreeNode currently does not accept monetary donations.
# If you would like to support the project, please:
#   - Submit new public data sources
#   - Improve documentation or code via Pull Request
#   - Help answer questions in Issues
#   - Share the project with others who study network protocols

github: # Not enabled
patreon: # Not enabled
open_collective: # Not enabled
ko_fi: # Not enabled
custom: []
