"""initial schema

Revision ID: 952132086a7b
Revises: 
Create Date: 2026-07-03 18:11:50.081730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952132086a7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw_link', sa.Text(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('auth_secret', sa.Text(), nullable=False),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('transport_config', sa.Text(), nullable=False),
    sa.Column('tls', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('last_latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('fail_reason', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index('idx_nodes_alive_region', ['is_alive', 'region'], unique=False)
        batch_op.create_index('idx_nodes_checked', ['last_checked_at'], unique=False)
        batch_op.create_index('idx_nodes_protocol_alive', ['protocol', 'is_alive'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_nodes_is_alive'), ['is_alive'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_protocol'), ['protocol'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_source_id'), ['source_id'], unique=False)

    op.create_table('proxy_sources',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('decode_base64', sa.Boolean(), nullable=False),
    sa.Column('proxy_scheme', sa.String(length=16), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_status', sa.String(length=16), nullable=True),
    sa.Column('last_nodes_added', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proxy_sources', schema=None) as batch_op:
        batch_op.create_index('idx_sources_enabled', ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_sources_enabled'), ['enabled'], unique=False)

    op.create_table('node_checks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('fail_reason', sa.String(length=64), nullable=True),
    sa.Column('raw_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_checks', schema=None) as batch_op:
        batch_op.create_index('idx_checks_node_time', ['node_id', 'checked_at'], unique=False)
        batch_op.create_index('idx_checks_time', ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_checks_node_id'), ['node_id'], unique=False)

    op.create_table('source_fetch_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['proxy_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_fetch_logs', schema=None) as batch_op:
        batch_op.create_index('idx_fetchlog_source_time', ['source_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_fetch_logs_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_fetch_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_fetch_logs_source_id'))
        batch_op.drop_index('idx_fetchlog_source_time')

    op.drop_table('source_fetch_logs')
    with op.batch_alter_table('node_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_checks_node_id'))
        batch_op.drop_index('idx_checks_time')
        batch_op.drop_index('idx_checks_node_time')

    op.drop_table('node_checks')
    with op.batch_alter_table('proxy_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proxy_sources_enabled'))
        batch_op.drop_index('idx_sources_enabled')

    op.drop_table('proxy_sources')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_source_id'))
        batch_op.drop_index(batch_op.f('ix_nodes_region'))
        batch_op.drop_index(batch_op.f('ix_nodes_protocol'))
        batch_op.drop_index(batch_op.f('ix_nodes_is_alive'))
        batch_op.drop_index(batch_op.f('ix_nodes_fingerprint'))
        batch_op.drop_index('idx_nodes_protocol_alive')
        batch_op.drop_index('idx_nodes_checked')
        batch_op.drop_index('idx_nodes_alive_region')

    op.drop_table('nodes')
    # ### end Alembic commands ###
